### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by saptisunil** [lgoodridge/serverless-chat#10]
at a.socket.onmessage (custom.js)

How can i solve that ?

**Comment by lgoodridge** [comment]
That means `data["messages"]` is undefined for some reason, likely because there is no "messages" key in the `data` object. I would try printing or inspecting the `data` object you received to see what keys are present. Also double check that you are sending a "messages" key in the [handler](https://github.com/lgoodridge/serverless-chat/blob/master/backend/handler.py#L187).
