### ISSUE TITLE
in _send_to_connection function, the cloudwatch needs domainName & stage, but as in the blog there is no mention on how to setup this api gateway domain name & stage, can you help with this issue? 

### ISSUE THREAD

**Issue by amitmaliik** [lgoodridge/serverless-chat#17]
def _send_to_connection(connection_id, data, event):
    gatewayapi = boto3.client("apigatewaymanagementapi",
            endpoint_url = "https://" + event["requestContext"]["domainName"] +
                    "/" + event["requestContext"]["stage"])
    return gatewayapi.post_to_connection(ConnectionId=connection_id,Data=json.dumps(data).encode('utf-8'))
 
the error that I get in Cloudwatch logs:

{
  "errorMessage": "'requestContext'",
  "errorType": "KeyError",
  "stackTrace": [
    "  File \"/var/task/handler.py\", line 244, in send_message\n    _send_to_connection(connectionID, data, event)\n",
    "  File \"/var/task/handler.py\", line 38, in _send_to_connection\n    endpoint_url = \"https://\" + event[\"requestContext\"][\"domainName\"] +\n"
  ]
}

**Comment by lgoodridge** [comment]
You shouldn't need to set it up yourself. Those values should be automatically provided and supplied in the event object passed to the handler.

That said, it looks like it's failing to instantiate the GatewayAPI client, because `requestContext` doesn't exist as a key on the `event` object, which is odd. My first guess would be to double check that you're sending the parameters in the correct order where you're using the function, but I don't think I can help debug much beyond that.

You can try logging the event object, to see which fields _are_ present, or if there's something obviously wrong.
